name: Publish Package
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on, e.g., master, main, develop

jobs:
  build-and-publish:
    runs-on: windows-latest  # Change this to the desired runner environment
    steps:
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#github-actions-notifications'
      
